import 'package:dun_s_application2/core/app_export.dart';import 'package:dun_s_application2/presentation/home_page/home_page.dart';import 'package:dun_s_application2/presentation/ng_n_ng_page/ng_n_ng_page.dart';import 'package:dun_s_application2/presentation/s_ki_n_page/s_ki_n_page.dart';import 'package:dun_s_application2/presentation/tin_t_c_page/tin_t_c_page.dart';import 'package:dun_s_application2/presentation/y_u_c_u_h_tr_xem_chi_ti_t_page/y_u_c_u_h_tr_xem_chi_ti_t_page.dart';import 'package:dun_s_application2/widgets/app_bar/appbar_image.dart';import 'package:dun_s_application2/widgets/app_bar/appbar_subtitle_1.dart';import 'package:dun_s_application2/widgets/app_bar/appbar_title.dart';import 'package:dun_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:dun_s_application2/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class SKiNTabContainerScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.gray5001, body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, child: Container(padding: getPadding(top: 18, bottom: 18), decoration: AppDecoration.white, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(45), leadingWidth: 48, leading: AppbarImage(height: getSize(32), width: getSize(32), svgPath: ImageConstant.imgArrowleftBlueGray900, margin: getMargin(left: 16, top: 6, bottom: 7), onTap: () => onTapArrowleft32(context)), centerTitle: true, title: AppbarTitle(text: "Tin tức & Sự kiện"), actions: [Padding(padding: getPadding(left: 17, right: 17), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgFilter, margin: getMargin(left: 6, right: 6)), AppbarSubtitle1(text: "Bộ lọc", margin: getMargin(top: 6))]))]), Container(height: getVerticalSize(60), width: getHorizontalSize(358), margin: getMargin(top: 17, bottom: 6), decoration: BoxDecoration(color: ColorConstant.gray5001, borderRadius: BorderRadius.circular(getHorizontalSize(20))), child: TabBar(labelColor: ColorConstant.whiteA700, labelStyle: TextStyle(fontSize: getFontSize(14), fontFamily: 'Inter', fontWeight: FontWeight.w700), unselectedLabelColor: ColorConstant.gray900, unselectedLabelStyle: TextStyle(fontSize: getFontSize(14), fontFamily: 'Inter', fontWeight: FontWeight.w700), indicatorPadding: getPadding(all: 8.0), indicator: BoxDecoration(borderRadius: BorderRadius.circular(getHorizontalSize(20)), gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [ColorConstant.indigo100, ColorConstant.indigoA200])), tabs: [Tab(child: Text("Tin tức", overflow: TextOverflow.ellipsis)), Tab(child: Text("Sự kiện", overflow: TextOverflow.ellipsis))]))]))), Container(width: double.maxFinite, child: Container(decoration: AppDecoration.fillGray5001, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(820), child: TabBarView(children: [TinTCPage(), SKiNPage()]))])))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Trangch: return AppRoutes.homePage; case BottomBarEnum.Chat: return "/"; case BottomBarEnum.Thngbo: return AppRoutes.yUCUHTrXemChiTiTPage; case BottomBarEnum.Tikhon: return AppRoutes.ngNNgPage; default: return "/";} } 
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.yUCUHTrXemChiTiTPage: return YUCUHTrXemChiTiTPage(); case AppRoutes.ngNNgPage: return NgNNgPage(); default: return DefaultWidget();} } 
onTapArrowleft32(BuildContext context) { Navigator.pop(context); } 
 }
