import '../home_th_ng_b_o_screen/widgets/listshape_item_widget.dart';import 'package:dun_s_application2/core/app_export.dart';import 'package:dun_s_application2/presentation/home_page/home_page.dart';import 'package:dun_s_application2/presentation/ng_n_ng_page/ng_n_ng_page.dart';import 'package:dun_s_application2/presentation/y_u_c_u_h_tr_xem_chi_ti_t_page/y_u_c_u_h_tr_xem_chi_ti_t_page.dart';import 'package:dun_s_application2/widgets/app_bar/appbar_image.dart';import 'package:dun_s_application2/widgets/app_bar/appbar_title.dart';import 'package:dun_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:dun_s_application2/widgets/custom_bottom_bar.dart';import 'package:dun_s_application2/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class HomeThNgBOScreen extends StatelessWidget {TextEditingController group275Controller = TextEditingController();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.gray5001, resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(118), width: double.maxFinite, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.center, child: Container(padding: getPadding(top: 24, bottom: 24), decoration: AppDecoration.white, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(69), leadingWidth: 48, leading: AppbarImage(height: getSize(32), width: getSize(32), svgPath: ImageConstant.imgArrowleftBlueGray900, margin: getMargin(left: 16), onTap: () => onTapArrowleft(context)), centerTitle: true, title: AppbarTitle(text: "Thông báo"), actions: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgCheckmarkGray900, margin: getMargin(left: 16, top: 4, right: 4)), AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgSettingsGray900, margin: getMargin(left: 16, top: 4, right: 20))])]))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: getPadding(left: 17), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomTextFormField(width: getHorizontalSize(70), focusNode: FocusNode(), controller: group275Controller, hintText: "Tất cả", variant: TextFormFieldVariant.UnderLineIndigoA700, fontStyle: TextFormFieldFontStyle.InterSemiBold16IndigoA700, textInputAction: TextInputAction.done), Padding(padding: getPadding(left: 16, bottom: 16), child: Text("Ưu đãi", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtInterMedium16Gray900)), Padding(padding: getPadding(left: 24, top: 1, bottom: 14), child: Text("Học phí", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtInterMedium16Gray900)), Padding(padding: getPadding(left: 24, top: 1, bottom: 14), child: Text("Cập nhật", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtInterMedium16Gray900))])))])), Container(width: double.maxFinite, child: Container(margin: getMargin(left: 16, top: 15, right: 16, bottom: 5), decoration: AppDecoration.fillGray5001, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(12));}, itemCount: 7, itemBuilder: (context, index) {return ListshapeItemWidget();})])))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Trangch: return AppRoutes.homePage; case BottomBarEnum.Chat: return "/"; case BottomBarEnum.Thngbo: return AppRoutes.yUCUHTrXemChiTiTPage; case BottomBarEnum.Tikhon: return AppRoutes.ngNNgPage; default: return "/";} } 
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.yUCUHTrXemChiTiTPage: return YUCUHTrXemChiTiTPage(); case AppRoutes.ngNNgPage: return NgNNgPage(); default: return DefaultWidget();} } 
onTapArrowleft(BuildContext context) { Navigator.pop(context); } 
 }
